### ISSUE TITLE
oppo R7 报错

### ISSUE THREAD

**Issue by tiefeiniu** [Tomzem/MultiLevelSelect#1]
04-02 11:11:43.014 21914-21914/com.haikou.meifang W/System.err: java.lang.IllegalStateException: Fatal Exception thrown on Scheduler

 at com.caveman.listcheckbox.utils.ListUtils.toListObject(ListUtils.java:36)
        at com.caveman.listcheckbox.adapter.ListViewAdapter.<init>(ListViewAdapter.java:40)
        at com.haikou.meifang.ui.workbench.custorlist.TreeCustorTurnSectionAcvitity.lambda$loadData$5$TreeCustorTurnSectionAcvitity(TreeCustorTurnSectionAcvitity.java:171)
        at com.haikou.meifang.ui.workbench.custorlist.TreeCustorTurnSectionAcvitity$$Lambda$5.accept(Unknown Source)
        at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:59)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)

**Comment by tiefeiniu** [comment]
List<Node> nodes = gson.fromJson(gson.toJson(list), new TypeToken<List<Node>>() {
            }.getType());
            return nodes;      这段代码报异常，在红米5 plu 上不报错

**Comment by Tomzem** [comment]
> List nodes = gson.fromJson(gson.toJson(list), new TypeToken<List>() {
> }.getType());
> return nodes; 这段代码报异常，在红米5 plu 上不报错

好的，谢谢 下班之后我看下

**Comment by tiefeiniu** [comment]
> List nodes = gson.fromJson(gson.toJson(list), new TypeToken() {
> }.getType());
> return nodes; 这段代码报异常，在红米5 plu 上不报错
> 
> 好的，谢谢 下班之后我看下

嗯，帮忙看看下了

**Comment by Tomzem** [comment]
(TreeCustorTurnSectionAcvitity.java:171)

> > List nodes = gson.fromJson(gson.toJson(list), new TypeToken() {
> > }.getType());
> > return nodes; 这段代码报异常，在红米5 plu 上不报错
> > 好的，谢谢 下班之后我看下
> 
> 嗯，帮忙看看下了

问题已经定位到了，只是我现在没办法修改 ，只能等晚上下班回去了

**Comment by tiefeiniu** [comment]
> (TreeCustorTurnSectionAcvitity.java:171)
> 
> 
> List nodes = gson.fromJson(gson.toJson(list), new TypeToken() {
> }.getType());
> return nodes; 这段代码报异常，在红米5 plu 上不报错
> 好的，谢谢 下班之后我看下
> 
> 嗯，帮忙看看下了
> 
> 问题已经定位到了，只是我现在没办法修改 ，只能等晚上下班回去了

没事，多谢了呀，那我晚上在看看，是不是内存溢出呀？java.lang.StackOverflowError，但是我不知道在哪改，等你更新了看看

**Comment by Tomzem** [comment]
com.haikou.meifang.ui.workbench.custorlist.TreeCustorTurnSectionAcvitity.lambda$loadData$5$TreeCustorTurnSectionAcvitity(TreeCustorTurnSectionAcvitity.java:171) 方便看一下这部分做了什么事情么？

**Comment by tiefeiniu** [comment]
> TreeCustorTurnSectionAcvitity

171     mAdapter = new ListViewAdapter(mLvMultiSelect, this, mItems, 0);  适配器初始化

**Comment by tiefeiniu** [comment]
public ListViewAdapter(ListView listView, Context context, List<T> datas, int defaultExpandLevel){
        super(listView, context, ListUtils.getInstance().toListObject(datas), defaultExpandLevel);
    }


  public List<Node> toListObject(List<T> list){
        Gson gson = new Gson();
//        List<Node> nodes = gson.fromJson(gson.toJson(list), new TypeToken<List<Node>>(){}.getType());
//        return nodes;


        if (gson.toJson(list) != null) {

            Type type = new TypeToken<List<Node>>() {
            }.getType();
            List<Node> nodes = new ArrayList<>();
            try {
              nodes = gson.fromJson(gson.toJson(list), type);
            }catch (Exception e){
                e.printStackTrace();
            }catch (Throwable e ){
                e.printStackTrace();
            }
            return nodes;

        }
        return  null;
    }
屏蔽的是你之前写的，后面我加上异常判断，没奔溃了，但是没数据，打log发现是内存溢出了，  nodes = gson.fromJson(gson.toJson(list), type);这句代码内存溢出了，但是使用高配机型就没事，就是说低内存的手机就会报内存溢出

**Comment by Tomzem** [comment]
> public ListViewAdapter(ListView listView, Context context, List datas, int defaultExpandLevel){
> super(listView, context, ListUtils.getInstance().toListObject(datas), defaultExpandLevel);
> }
> 
> public List toListObject(List list){
> Gson gson = new Gson();
> // List nodes = gson.fromJson(gson.toJson(list), new TypeToken<List>(){}.getType());
> // return nodes;
> 
> ```
>     if (gson.toJson(list) != null) {
> 
>         Type type = new TypeToken<List<Node>>() {
>         }.getType();
>         List<Node> nodes = new ArrayList<>();
>         try {
>           nodes = gson.fromJson(gson.toJson(list), type);
>         }catch (Exception e){
>             e.printStackTrace();
>         }catch (Throwable e ){
>             e.printStackTrace();
>         }
>         return nodes;
> 
>     }
>     return  null;
> }
> ```
> 屏蔽的是你之前写的，后面我加上异常判断，没奔溃了，但是没数据，打log发现是内存溢出了， nodes = gson.fromJson(gson.toJson(list), type);这句代码内存溢出了，但是使用高配机型就没事，就是说低内存的手机就会报内存溢出

你好，我优化了一下，你可以重新试一下1.0.4的版本，如果有问题 可以继续留言。这个项目写的有点久了，当时技术能力有限。后面我会找时间把整个项目重新优化。

**Comment by tiefeiniu** [comment]
> public ListViewAdapter(ListView listView, Context context, List datas, int defaultExpandLevel){
> super(listView, context, ListUtils.getInstance().toListObject(datas), defaultExpandLevel);
> }
> public List toListObject(List list){
> Gson gson = new Gson();
> // List nodes = gson.fromJson(gson.toJson(list), new TypeToken(){}.getType());
> // return nodes;
>     if (gson.toJson(list) != null) {
> 
>         Type type = new TypeToken<List<Node>>() {
>         }.getType();
>         List<Node> nodes = new ArrayList<>();
>         try {
>           nodes = gson.fromJson(gson.toJson(list), type);
>         }catch (Exception e){
>             e.printStackTrace();
>         }catch (Throwable e ){
>             e.printStackTrace();
>         }
>         return nodes;
> 
>     }
>     return  null;
> }
> 
> 屏蔽的是你之前写的，后面我加上异常判断，没奔溃了，但是没数据，打log发现是内存溢出了， nodes = gson.fromJson(gson.toJson(list), type);这句代码内存溢出了，但是使用高配机型就没事，就是说低内存的手机就会报内存溢出
> 
> 你好，我优化了一下，你可以重新试一下1.0.4的版本，如果有问题 可以继续留言。这个项目写的有点久了，当时技术能力有限。后面我会找时间把整个项目重新优化。


我替换了这里，但还是报同样的错，
 public List<Node> toListObject(List<T> list){
        Gson gson = new Gson();
        String listJson = gson.toJson(list);
        List<Node> nodes = gson.fromJson(listJson, new TypeToken<List<Node>>(){}.getType());
        return nodes;
    }

**Comment by Tomzem** [comment]
> > public ListViewAdapter(ListView listView, Context context, List datas, int defaultExpandLevel){
> > super(listView, context, ListUtils.getInstance().toListObject(datas), defaultExpandLevel);
> > }
> > public List toListObject(List list){
> > Gson gson = new Gson();
> > // List nodes = gson.fromJson(gson.toJson(list), new TypeToken(){}.getType());
> > // return nodes;
> > if (gson.toJson(list) != null) {
> > ```
> >     Type type = new TypeToken<List<Node>>() {
> >     }.getType();
> >     List<Node> nodes = new ArrayList<>();
> >     try {
> >       nodes = gson.fromJson(gson.toJson(list), type);
> >     }catch (Exception e){
> >         e.printStackTrace();
> >     }catch (Throwable e ){
> >         e.printStackTrace();
> >     }
> >     return nodes;
> > 
> > }
> > return  null;
> > ```
> > }
> > 屏蔽的是你之前写的，后面我加上异常判断，没奔溃了，但是没数据，打log发现是内存溢出了， nodes = gson.fromJson(gson.toJson(list), type);这句代码内存溢出了，但是使用高配机型就没事，就是说低内存的手机就会报内存溢出
> > 你好，我优化了一下，你可以重新试一下1.0.4的版本，如果有问题 可以继续留言。这个项目写的有点久了，当时技术能力有限。后面我会找时间把整个项目重新优化。
> 
> 我替换了这里，但还是报同样的错，
> public List toListObject(List list){
> Gson gson = new Gson();
> String listJson = gson.toJson(list);
> List nodes = gson.fromJson(listJson, new TypeToken<List>(){}.getType());
> return nodes;
> }

public List toListObject(List list) 你这里直接用List？

**Comment by tiefeiniu** [comment]
> public ListViewAdapter(ListView listView, Context context, List datas, int defaultExpandLevel){
> super(listView, context, ListUtils.getInstance().toListObject(datas), defaultExpandLevel);
> }
> public List toListObject(List list){
> Gson gson = new Gson();
> // List nodes = gson.fromJson(gson.toJson(list), new TypeToken(){}.getType());
> // return nodes;
> if (gson.toJson(list) != null) {
>     Type type = new TypeToken<List<Node>>() {
>     }.getType();
>     List<Node> nodes = new ArrayList<>();
>     try {
>       nodes = gson.fromJson(gson.toJson(list), type);
>     }catch (Exception e){
>         e.printStackTrace();
>     }catch (Throwable e ){
>         e.printStackTrace();
>     }
>     return nodes;
> 
> }
> return  null;
> 
> }
> 屏蔽的是你之前写的，后面我加上异常判断，没奔溃了，但是没数据，打log发现是内存溢出了， nodes = gson.fromJson(gson.toJson(list), type);这句代码内存溢出了，但是使用高配机型就没事，就是说低内存的手机就会报内存溢出
> 你好，我优化了一下，你可以重新试一下1.0.4的版本，如果有问题 可以继续留言。这个项目写的有点久了，当时技术能力有限。后面我会找时间把整个项目重新优化。
> 
> 我替换了这里，但还是报同样的错，
> public List toListObject(List list){
> Gson gson = new Gson();
> String listJson = gson.toJson(list);
> List nodes = gson.fromJson(listJson, new TypeToken(){}.getType());
> return nodes;
> }
> 
> public List toListObject(List list) 你这里直接用List？

没有，public List<Node> toListObject(List<T> list)，是这个，写错了

**Comment by Tomzem** [comment]
> list

1.https://blog.csdn.net/shoneworn/article/details/82890344，你可以看下这个问题。
2.如果你的json是来自文件的话，建议使用Reader
Gson gson = new Gson();
Reader reader = new FileReader("/path/file");
nodes = gson.fromJson(reader， type);

**Comment by tiefeiniu** [comment]
> list
> 
> 1.https://blog.csdn.net/shoneworn/article/details/82890344，你可以看下这个问题。
> 2.如果你的json是来自文件的话，建议使用Reader
> Gson gson = new Gson();
> Reader reader = new FileReader("/path/file");
> nodes = gson.fromJson(reader， type);

我用阿里巴巴的fastjson 解决了，用这些代码替换原先的gson转化操作, 另外fastjson适合操作大内存的json数据。
 public List<Node> toListObject(List<T> list){
        String userStr = JSON.toJSONString(list);
        List<Node> userList = JSON.parseArray(userStr, Node.class);
        return  userList;
}

**Comment by tiefeiniu** [comment]
> list
> 1.https://blog.csdn.net/shoneworn/article/details/82890344，你可以看下这个问题。
> 2.如果你的json是来自文件的话，建议使用Reader
> Gson gson = new Gson();
> Reader reader = new FileReader("/path/file");
> nodes = gson.fromJson(reader， type);
> 
> 我的json不是来自文件的；我用阿里巴巴的fastjson 解决了，用这些代码替换原先的gson转化操作, 另外fastjson适合操作大内存的json数据。
> public List toListObject(List list){
> String userStr = JSON.toJSONString(list);
> List userList = JSON.parseArray(userStr, Node.class);
> return  userList;
> }

不小心点关了

**Comment by tiefeiniu** [comment]
- [ ]
